### ISSUE TITLE
Ability to convert medium blog to writr format

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/writr#60]
As a consumer that is looking to migrate from medium to writr I would like to run a CLI command to migrate to writr including the blog documents and images.

**Comment by christianllv** [comment]
Medium doesn't have APIs, then I can use the user feed to fetch the content, but I can get the last 10 post, no more.

**Comment by jaredwray** [comment]
OK... I thought they had an export content button and zip file. Is there?

**Comment by jaredwray** [comment]
Export articles from Medium
Exporting the content of your Medium blog takes place in HTML format and not XML. That and the differences in the RSS feed conventions make the importing of content to WordPress.org a challenge and you would need to take a roundabout approach to counter the format incompatibility.

Exporting content itself is an easy task. All you need to do is open the user settings, click on the “Account” section and scroll down and click on “Download your information”. A .zip file of all the blogs and content you have shared on Medium, the posts and drafts that you have, the information available on your profile page will be sent to your registered email id in the form of HTML files.

Export the articles from Medium

The link will be active for a period of 24 hours after the email is received. Medium also gives you the option to change the email id when you export your content from it.

**Comment by christianllv** [comment]
I will try that and works based on that zip file

**Comment by christianllv** [comment]
Pull request to implement this feature: #80
