### ISSUE TITLE
Upgrade node-fetch

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/writr#66]
node-fetch   ^2.6.6  →   ^3.2.2

**Comment by christianllv** [comment]
@jaredwray Actually node-fetch 3.2.2 has a breaking changes and I saw multiple post related of this including Typescript config, but none runs. Another alternative to get an update module is use```axios```  instead ```node-fetch ```. Please, let me know your thoughts.

**Comment by jaredwray** [comment]
Please move to axios if needed.
