### ISSUE TITLE
ability to serve the site from a command line

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/writr#70]
as a user I would like to be able to serve the site from the cli and have it run a express web server instance on the distributed folder `blog_output` when the command is issued:

```bash
writr serve
```

by default it will serve on port `3000` but you can specify the port by doing:

```bash
writr serve --port 8080
```

**Comment by christianllv** [comment]
@jaredwray I think that the best way to do this is using Browser-sync. I can personalize to show the app name, silet mode and APIs to handle the actions.

**Comment by jaredwray** [comment]
that would be great.
